# /config/yaml_mappings/product_magento_woo.yaml
source: magento
target: woocommerce
entity: product
description: Mapping definition from Magento Product structure to WooCommerce Product structure.

fields:
  # Trường đích (Woo) : JMESPath Query (Magento)
  #  Thông tin cơ bản:
  sku: sku
  name: name
  type: type_id
  status: status
  short_description: short_description
  catalog_visibility: visibility
  categories: "extension_attributes.category_links[*].{id: category_id}"

  #  Giá cả
  regular_price: price
  sale_price: special_price


transformations:
  #  Thông tin cơ bản
  name:
    - type: function
      function_name: normalize_string_mapper
      params:
        value: $SOURCE_VALUE
  type:
    - type: function
      function_name: transform_magento_value
      params:
        value: $SOURCE_VALUE
        source_platform: magento
        target_platform: woo
        entity: product
        field: type_id
        default_value: simple
  status:
    - type: function
      function_name: transform_magento_value
      params:
        value: $SOURCE_VALUE
        source_platform: magento
        target_platform: woo
        entity: product
        field: status
        default_value: draft
  catalog_visibility:
    - type: function
      function_name: transform_magento_value
      params:
        value: $SOURCE_VALUE
        source_platform: magento
        target_platform: woo
        entity: product
        field: visibility
        default_value: visible
  categories:
    - type: function
      function_name: map_ids_to_target
      params:
        entity: category
        source_ids: $SOURCE_VALUE
        context: $CONTEXT
  # Giá cả
  regular_price:
    - type: function
      function_name: normalize_string_mapper
      params:
        value: $SOURCE_VALUE
  sale_price:
    - type: function
      function_name: normalize_string_mapper
      params:
        value: $SOURCE_VALUE

post_processors:
  - type: function
    function_name: save_id_mapping
    params:
      created_target_record: $CREATED_TARGET_RECORD
      source_record: $SOURCE_RECORD
      source_id_field: id
      target_id_field: id
      entity: product
      context: $CONTEXT